[theme]
base = "dark"
primaryColor = "#00c44f"
backgroundColor = "#080f1e"
secondaryBackgroundColor = "#0d1a30"
textColor = "#dde6f5"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
